<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
(require __DIR__.'/Zero1_MagentoDev_KernelDevDebugContainer.php')->set(\ContainerXNzEaRv\Zero1_MagentoDev_KernelDevDebugContainer::class, null);
require __DIR__.'/ContainerXNzEaRv/getApplicationService.php';

$classes = [];
$classes[] = 'Symfony\Component\Console\Application';
$classes[] = 'Zero1\MagentoDev\Command\Config\Show';
$classes[] = 'Zero1\MagentoDev\Service\Composer';
$classes[] = 'Zero1\MagentoDev\Service\Git';
$classes[] = 'Zero1\MagentoDev\Command\Make\CliCommand';
$classes[] = 'Zero1\MagentoDev\Service\Module';
$classes[] = 'Zero1\MagentoDev\Factory\FileSystemFactory';
$classes[] = 'Zero1\MagentoDev\Command\Make\Controller';
$classes[] = 'Zero1\MagentoDev\Service\Magento\Routes';
$classes[] = 'Zero1\MagentoDev\Service\Magento\ObjectManager';
$classes[] = 'Zero1\MagentoDev\Command\Make\Model';
$classes[] = 'Zero1\MagentoDev\Command\Make\Module';
$classes[] = 'Zero1\MagentoDev\Command\Make\Observer';
$classes[] = 'Zero1\MagentoDev\Service\Magento\Events';
$classes[] = 'Zero1\MagentoDev\Service\TemplateRenderer';
$classes[] = 'Zero1\MagentoDev\Command\Module\WorkOn';
$classes[] = 'Zero1\MagentoDev\Service\ModuleList';
$classes[] = 'Zero1\MagentoDev\Command\Vendor\Diff';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

$preloaded = Preloader::preload($classes);
