<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNzEaRv\Zero1_MagentoDev_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNzEaRv/Zero1_MagentoDev_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNzEaRv.legacy');

    return;
}

if (!\class_exists(Zero1_MagentoDev_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNzEaRv\Zero1_MagentoDev_KernelDevDebugContainer::class, Zero1_MagentoDev_KernelDevDebugContainer::class, false);
}

return new \ContainerXNzEaRv\Zero1_MagentoDev_KernelDevDebugContainer([
    'container.build_hash' => 'XNzEaRv',
    'container.build_id' => '3ea2a138',
    'container.build_time' => 1759939872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNzEaRv');
