<?php

namespace ContainerXjMkFN8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationService extends srcZero1_MagentoDev_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symfony\Component\Console\Application' shared autowired service.
     *
     * @return \Symfony\Component\Console\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Command/Module/WorkOn.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ModuleList.php';

        $container->services['Symfony\\Component\\Console\\Application'] = $instance = new \Symfony\Component\Console\Application();

        $instance->add(new \Zero1\MagentoDev\Command\Module\WorkOn(new \Zero1\MagentoDev\Service\ModuleList()));

        return $instance;
    }
}
