<?php

namespace ContainerXNzEaRv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationService extends Zero1_MagentoDev_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symfony\Component\Console\Application' shared autowired service.
     *
     * @return \Symfony\Component\Console\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ResetInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Application.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Config/Show.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Composer.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Git.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Make/CliCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Module.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/FileSystemFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Make/Controller.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Magento/Routes.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Magento/ObjectManager.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Make/Model.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Make/Module.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Make/Observer.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Magento/Events.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TemplateRenderer.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Module/WorkOn.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ModuleList.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Vendor/Diff.php';

        $container->services['Symfony\\Component\\Console\\Application'] = $instance = new \Symfony\Component\Console\Application();

        $a = new \Zero1\MagentoDev\Service\Composer();
        $b = new \Zero1\MagentoDev\Service\Git();
        $c = new \Zero1\MagentoDev\Factory\FileSystemFactory();

        $d = new \Zero1\MagentoDev\Service\Module($c);
        $e = new \Zero1\MagentoDev\Service\Magento\Routes($c, new \Zero1\MagentoDev\Service\Magento\ObjectManager($c));

        $instance->add(new \Zero1\MagentoDev\Command\Config\Show($a, $b));
        $instance->add(new \Zero1\MagentoDev\Command\Make\CliCommand($d));
        $instance->add(new \Zero1\MagentoDev\Command\Make\Controller($d, $e));
        $instance->add(new \Zero1\MagentoDev\Command\Make\Model($a, $b));
        $instance->add(new \Zero1\MagentoDev\Command\Make\Module($a, $b));
        $instance->add(new \Zero1\MagentoDev\Command\Make\Observer($d, $e, new \Zero1\MagentoDev\Service\Magento\Events(new \Zero1\MagentoDev\Service\TemplateRenderer())));
        $instance->add(new \Zero1\MagentoDev\Command\Module\WorkOn(new \Zero1\MagentoDev\Service\ModuleList()));
        $instance->add(new \Zero1\MagentoDev\Command\Vendor\Diff());

        return $instance;
    }
}
