<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjMkFN8\srcZero1_MagentoDev_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjMkFN8/srcZero1_MagentoDev_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjMkFN8.legacy');

    return;
}

if (!\class_exists(srcZero1_MagentoDev_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjMkFN8\srcZero1_MagentoDev_KernelDevDebugContainer::class, srcZero1_MagentoDev_KernelDevDebugContainer::class, false);
}

return new \ContainerXjMkFN8\srcZero1_MagentoDev_KernelDevDebugContainer([
    'container.build_hash' => 'XjMkFN8',
    'container.build_id' => '132191ff',
    'container.build_time' => 1695118586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjMkFN8');
