<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require '/home/magento/htdocs/vendor/autoload.php';
(require __DIR__.'/srcZero1_MagentoDev_KernelDevDebugContainer.php')->set(\ContainerXjMkFN8\srcZero1_MagentoDev_KernelDevDebugContainer::class, null);
require __DIR__.'/ContainerXjMkFN8/getApplicationService.php';

$classes = [];
$classes[] = 'Symfony\Component\Console\Application';
$classes[] = 'Zero1\MagentoDev\Command\Module\WorkOn';
$classes[] = 'Zero1\MagentoDev\Service\ModuleList';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

$preloaded = Preloader::preload($classes);
